== C:\Users\lenovo\Desktop\20250906 charls  klosa\project_name\03_scripts\14_final_eval_s7.py == 2025-10-10 03:22:47

Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\20250906 charls  klosa\project_name\03_scripts\14_final_eval_s7.py", line 701, in <module>
    main()
  File "C:\Users\lenovo\Desktop\20250906 charls  klosa\project_name\03_scripts\14_final_eval_s7.py", line 523, in main
    df = pd.read_csv(MEAN_MODE_XY)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lenovo\\Desktop\\20250906 charls  klosa\\project_name\\02_processed_data\\v2025-10-01\\frozen\\charls_mean_mode_Xy.csv'

[exit] code=1
